src/Entity/JobOffer.php
<?php

namespace App\Entity;

use App\Repository\JobOfferRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=JobOfferRepository::class)
 */
class JobOffer
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class , inversedBy="JobOffers")
     * @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
     */
    private $client;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string")
     */
    private $note;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $location;

    /**
     * @ORM\Column(type="datetime")
     */
    private $closing_date;

    /**
     * @ORM\Column(type="integer")
     */
    private $salary;

    /**
     * @ORM\Column(type="datetime")
     */
    private $creation_date;

    /**
     * @ORM\ManyToOne(targetEntity=JobCategory::class, inversedBy="JobOffer")
     * @ORM\JoinColumn(nullable=true , onDelete="SET NULL")
     */
    private $job_cat;

    /**
     * @ORM\ManyToOne(targetEntity=JobTypes::class, inversedBy="JobOffer")
     * @ORM\JoinColumn(nullable=false)
     */
    private $job_type;

    /**
     * @ORM\OneToMany(targetEntity=Candidature::class, mappedBy="job_offer")
     */
    private $candidatures;

    public function __construct()
    {
        $this->candidatures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getNote(): ?string
    {
        return $this->note;
    }

    public function setNote(string $note): self
    {
        $this->note = $note;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getClosingDate(): ?\DateTimeInterface
    {
        return $this->closing_date;
    }

    public function setClosingDate(\DateTimeInterface $closing_date): self
    {
        $this->closing_date = $closing_date;

        return $this;
    }

    public function getSalary(): ?int
    {
        return $this->salary;
    }

    public function setSalary(int $salary): self
    {
        $this->salary = $salary;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTimeInterface $creation_date): self
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function getJobCat(): ?JobCategory
    {
        return $this->job_cat;
    }

    public function setJobCat(JobCategory $job_cat): self
    {
        $this->job_cat = $job_cat;

        return $this;
    }

    public function getJobType(): ?JobTypes
    {
        return $this->job_type;
    }

    public function setJobType(JobTypes $job_type): self
    {
        $this->job_type = $job_type;

        return $this;
    }

    /**
     * @return Collection|Candidature[]
     */
    public function getCandidatures(): Collection
    {
        return $this->candidatures;
    }

    public function addCandidature(Candidature $candidature): self
    {
        if (!$this->candidatures->contains($candidature)) {
            $this->candidatures[] = $candidature;
            $candidature->setJobOffer($this);
        }

        return $this;
    }

    public function removeCandidature(Candidature $candidature): self
    {
        if ($this->candidatures->removeElement($candidature)) {
            // set the owning side to null (unless already changed)
            if ($candidature->getJobOffer() === $this) {
                $candidature->setJobOffer(null);
            }
        }

        return $this;
    }
    
    public function __toString(): string
    {
        return $this->getJobCat();
    }
}

src/Form/JobOfferType.php
<?php

namespace App\Form;

use App\Entity\Client;
use App\Entity\JobCategory;
use App\Entity\JobOffer;
use App\Entity\JobTypes;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;



class JobOfferType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('note')
            ->add('location')
            ->add('closing_date', DateType::class, [
                'widget' => 'single_text'])
            ->add('salary')
            ->add('client', EntityType::class, [
                'class' => Client::class,
                'required' => false
            ])
            ->add('job_cat', EntityType::class, [
                'class' => JobCategory::class,
            ])
            ->add('job_type', EntityType::class, [
                'class' => JobTypes::class,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => JobOffer::class,
        ]);
    }
}

src/Controller/JobOfferController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\JobTypes;
use App\Entity\JobOffer;
use App\Form\JobOfferType;
use App\Repository\CandidatureRepository;
use App\Repository\JobCategoryRepository;
use App\Repository\JobOfferRepository;
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

/**
 * @Route("/job/offer")
 */
class JobOfferController extends AbstractController
{
   /**
     * @Route("/", name="job_offer_index", methods={"GET"})
     */
    public function index(JobOfferRepository $jobOfferRepository, JobCategoryRepository $jobCategoryRepository): Response
    {
       
        $user = $this->getUser();

        $allJobCategory = $jobCategoryRepository->findAll();
        return $this->render('job_offer/index.html.twig', [
            'job_offers' => $jobOfferRepository->findAll(),
            'user' => $user,
            'categories' => $allJobCategory,
        ]);
    }

    /**
     * @Route("/new", name="job_offer_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $jobOffer = new JobOffer();
        $form = $this->createForm(JobOfferType::class, $jobOffer);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {

            $jobOffer->setCreationDate(new DateTime());
            
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($jobOffer);
            $entityManager->flush();

            return $this->redirectToRoute('job_offer_index');
        }

        return $this->render('job_offer/new.html.twig', [
            'job_offer' => $jobOffer,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="job_offer_show", methods={"GET"})
     */
    public function show(
        JobOffer $jobOffer, 
        JobOfferRepository $jobOfferRepository, 
        CandidatureRepository $candidatureRepository,
        Security $security
        ): Response
    {
        /** @var User */
        $user = $security->getUser();
        $jobBefore = $jobOfferRepository->getPreviousJob($jobOffer);
        $jobAfter = $jobOfferRepository->getNextJob($jobOffer);
        $user->setCandidat($user->getCandidat());
        $jobTypeRepository = $this->getDoctrine()
        ->getRepository(JobTypes::class);

        $jobType = $jobTypeRepository->findOneBy(['id' => $jobOffer->getJobType()]);

        return $this->render('job_offer/show.html.twig', [
            'job_offer' => $jobOffer,
            'job_type' => $jobType,
            'job_previous'=> $jobBefore,
            'job_next'=> $jobAfter,
        // convertir candidature en Boolean
            'candidatureExists' => !! $candidatureRepository->findOneBy([
                'job_offer'=> $jobOffer->getId(),
                'candidat'=> $user->getCandidat()->getId(),
            ])
        ]);
    }

    /**
     * @Route("/{id}/edit", name="job_offer_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, JobOffer $jobOffer): Response
    {
        $form = $this->createForm(JobOfferType::class, $jobOffer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('job_offer_index');
        }

        return $this->render('job_offer/edit.html.twig', [
            'job_offer' => $jobOffer,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="job_offer_delete", methods={"POST"})
     */
    public function delete(Request $request, JobOffer $jobOffer): Response
    {
        if ($this->isCsrfTokenValid('delete'.$jobOffer->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($jobOffer);
            $entityManager->flush();
        }

        return $this->redirectToRoute('job_offer_index');
    }
}

templates/job_offer/_delete_form.html.twig
<form method="post" action="{{ path('job_offer_delete', {'id': job_offer.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ job_offer.id) }}">
    <button class="btn bn-lg gradient red darken-3 btn-block waves-effect waves-light btn-register">Delete</button>
</form>

templates/job_offer/_form.html.twig
{% block stylesheets %}

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <style>
        .dropdown-content{
            max-height: none;
        } 
        .tp-caption.boxshadow, .boxshadow {
                box-shadow: 0 0 0px rgb(0 0 0)!important;
        }
    </style>

{% endblock %}

{{ form_start(form) }}
    
   <section class="section-padding">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-6">
                    <div class="input-field">
                        {{ form_widget(form.title) }}
                        {{ form_label(form.title, 'title', {
                            'label_attr': {'class': 'title'}
                        }) }}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6">   
                    <div class="input-field">
                       {{ form_widget(form.description) }}
                        {{ form_label(form.description, 'description', {
                            'label_attr': {'class': 'description'}
                        }) }}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6">
                    <div class="input-field">
                        {{ form_widget(form.note) }}
                        {{ form_label(form.note, 'note', {
                            'label_attr': {'class': 'note'}
                        }) }}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6">
                    <div class="input-field">
                        {{ form_widget(form.location) }}
                        {{ form_label(form.location, 'location', {
                            'label_attr': {'class': 'location'}
                        }) }}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6">
                    <div class="input-field">
                        {{ form_widget(form.closing_date) }}
                        {{ form_label(form.closing_date, 'closing_date', {
                            'label_attr': {'class': 'closing_date'}
                        }) }}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6">
                    <div class="input-field">
                        {{ form_widget(form.salary) }}
                        {{ form_label(form.salary, 'salary', {
                            'label_attr': {'class': 'salary'}
                        }) }}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6">
                    <div class="input-field">
                        {{ form_widget(form.client) }}
                        {{ form_label(form.client, 'client', {
                            'label_attr': {'class': 'client'}
                        }) }}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6">
                    <div class="input-field">
                         {{ form_widget(form.job_cat) }}
                            {{ form_label(form.job_cat, 'job_cat', {
                            'label_attr': {'class': 'job_cat'}
                        }) }}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6">
                    <div class="input-field">
                        {{ form_widget(form.job_type) }}
                        {{ form_label(form.job_type, 'job_type', {
                            'label_attr': {'class': 'job_type'}
                        }) }}
                    </div>
                </div>
                <div class="col-xs-12 ">
                    <button type="submit" class="btn btn-block btn-lg gradient secondary waves-effect waves-light">
                        <span><strong>CREATE</strong> NOW</span>
                    </button>
                </div>
            </div>
        </section>

   
{{ form_end(form) }}

{% block javascripts %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <script>
        $(document).ready(function(){
            $('select').formSelect();
        });
    </script>
    <script>
        $('.datepicker').datepicker({
            format: 'yyyy-mm-dd' });
    </script>

{% endblock %}

templates/job_offer/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit JobOffer{% endblock %}

{% block body %}
    <h1 style="padding-top:10rem; text-align:center; background-color:#2F3138; margin-top:0; color:white; padding-bottom:2%">Edit JobOffer</h1>

    {{ include('job_offer/_form.html.twig', {'button_label': 'Update'}) }}

     <a target="_self" href="{{ path('admin_job_offer_index') }}" class="btn bn-lg gradient secondary btn-block waves-effect waves-light btn-register">
        <span> back to list</span>
    </a>

    {{ include('job_offer/_delete_form.html.twig') }}
{% endblock %}

templates/job_offer/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}JobOffer index{% endblock %}

{% block body %}
   
  <div class="base">

    <!-- Page -->
    <div class="page">

        <!-- Page Header-->
        <section class="page-title page-title-bg fixed-bg overlay dark-5 padding-top-160 padding-bottom-80">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h2 class="white-text">Our job offers</h2>
                        <span class="white-text">Search and filter by job category</span>
                    </div>
                </div>
            </div>
        </section>


        <!-- Page Content-->
        <section id="job-offers" class="section-padding gray-bg">
            <div class="container">
                <div class="text-center mb-40">
                    <h2 class="section-title">We have the perfect job for you</h2>
                    <p class="section-sub">just like our candidates, we offer quality, serious & reliable job offers.</p>
                </div>
                <div class="portfolio-container">
                    <ul class="portfolio-filter brand-filter text-center">
                        <li class="active waves-effect waves-light" data-group="all">All</li>
                        {% for category in categories %}
                            <li class=" waves-effect waves-light" data-group="{{category.category}}">{{category.category}}</li>
                        {% endfor %}
                    </ul>
                    <div class="portfolio portfolio-with-title col-2 gutter mt-30">

                    {% for oneOfAllOffer in job_offers %}
                        <div class="portfolio-item" data-groups='["all", "{{oneOfAllOffer.jobCat.category}}"]'>
                            <div class="portfolio-wrapper">
                                <div class="card job-card">
                                    <div class="card-content">
                                        <span class="title">
                                            <span class="card-title">{{ oneOfAllOffer.title }}</span>
                                            <span class="ref grey-text">{{ oneOfAllOffer.id }}</span>
                                        </span>
                                        <div class="metas mb-20">
                                            <div class="meta">
                                                <i class="material-icons">&#xE53E;</i>{{ oneOfAllOffer.salary }}&euro;
                                            </div>
                                            <div class="meta">
                                                <i class="material-icons">&#xE916;</i>{{ oneOfAllOffer.closingDate|date('d/m/Y') }}
                                            </div>
                                            <div class="meta">
                                                <i class="material-icons">&#xE55F;</i>{{ oneOfAllOffer.location }}
                                            </div>
                                        </div>
                                        <p class="truncate-text">{{ oneOfAllOffer.description }}</p>
                                    </div>
                                    <div class="card-action">
                                        <a class="btn btn-md primary border waves-effect waves-dark" href="{{ path ('job_offer_show', {'id': oneOfAllOffer.id}) }}">Details</a>
                                        <a class="btn btn-md primary waves-effect waves-light" href="">Apply</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
        </section>

        <section class="cta-candidate bg-fixed bg-cover overlay dark-5 padding-top-70 padding-bottom-50">
            <div class="container">
                <div class="row">
                    <div class="valign-wrapper text-center">
                        <div class="hero-intro valign-cell">
                            <h2 class="tt-headline clip is-full-width no-margin">
                                <span>You are </span>
                                <span class="tt-words-wrapper">
                                    <b class="is-visible">Commercial</b>
                                    <b>Creative</b>
                                    <b>Marketing & PR</b>
                                    <b>Technology</b>
                                    <b>Fashion & luxury</b>
                                    <b>Retail sales</b>
                                </span>
                            </h2>
                            <h3 class="c-secondary mb-30 no-margin">Sign-up and apply for jobs now</h3>
                            <p class="white-text section-sub">Each one of your skills is seen as precious resource to us, each one of your personality traits are considered as an added on value. Joining us is allowing our recruitment expertise and personal guidance to bring the best out in you by choosing the most suited position.</p>

                            <a href="/register.html" class="btn border secondary waves-effect waves-light mt-40">Join us</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </div>

</div>


{% endblock %}

templates/job_offer/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New JobOffer{% endblock %}

{% block body %}
    <h1 style="padding-top:10rem; text-align:center; background-color:#2F3138; margin-top:0; color:white; padding-bottom:2%">Create new JobOffer</h1>

    {{ include('job_offer/_form.html.twig') }}

    <a target="_self" href="{{ path('admin_job_offer_index') }}" class="btn bn-lg gradient secondary btn-block waves-effect waves-light btn-register">
        <span> back to list</span>
    </a>

{% endblock %}

templates/job_offer/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}JobOffer{% endblock %}

{% block body %}
    <h1 style="padding-top:10rem; text-align:center; background-color:#2F3138; margin-top:0; color:white; padding-bottom:2%">JobOffer</h1>

    <div class="base">

    <!-- Page -->
    <div class="page">

        <!-- Page Header-->
        <section class="page-title page-title-bg fixed-bg overlay dark-5 padding-top-160 padding-bottom-80">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h2 class="white-text">{{job_offer.title}}</h2>
                        <span class="white-text">{{job_offer.id}}</span>
                        <ol class="breadcrumb">
                            <li>
                                <div class="portfolio-nav">
                                    {% if job_previous|length != 0 %}
                                        <a href="{{path('job_offer_show', { id: job_previous[0].id })}}" class="waves-effect waves-dark"><i class="fa fa-angle-left" aria-hidden="true"></i> Prev</a>
                                    {% endif %}
                                        <a href="{{ path('job_offer_index') }}" class="waves-effect waves-dark"><i class="fa fa-th-large" aria-hidden="true"></i></a>
                                    {% if job_next|length != 0 %}
                                        <a href="{{path('job_offer_show', { id: job_next[0].id })}}" class="waves-effect waves-dark">Next <i class="fa fa-angle-right" aria-hidden="true"></i></a>
                                    {% endif %}
                                </div>
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </section>

        <!-- Page Content-->
        <section class="single-project-section section-padding light-gray-bg">
            <div class="container">
                <div class="project-overview">
                    <div class="row mb-80">
                        <div class="col-xs-12 col-md-8">
                            <p class="ref grey-text no-margin">{{job_offer.id}}</p>
                            <h2>{{job_offer.title}}</h2>
                            <p>{{job_offer.description}}</p>
                            
                        </div>

                        <div class="col-xs-12 col-md-4 quick-overview">
                            <ul class="portfolio-meta">
                                <li><span> Published at </span>{{job_offer.creationDate|date('d/m/Y')}}</li>
                
                                <li><span> Contract Type </span>{{job_offer.jobType}}</li>
                                <li><span> Salary </span>{{job_offer.salary}} &euro;</li>
                                <li><span> Location </span>{{job_offer.location}}</li>
                                <li><span> Closing date </span>{{job_offer.closingDate|date('d/m/Y')}}</li>
                            </ul>
                            

                             {% if is_granted('ROLE_ADMIN') %}
                                    <a style="width:23.5vw; height:8vh; font-size:3rem; " class="btn gradient secondary waves-effect waves-light btn-register" href="{{ path('job_offer_edit', {'id': job_offer.id}) }}">edit</a>
                             {% else %}
                                    {% if candidatureExists %}
                                        <div class="btn btn-block btn-success mt-30 waves-effect waves-light disabled">You have applied for this job</div>
                                    {% else %}
                                        <a class="btn btn-block gradient primary mt-30 waves-effect waves-light" href="{{ path ('candidature_new', {id:job_offer.id})}}">Apply for this job</a>
                                    {% endif %}
                             {% endif %}
                        </div>
                    </div>
                </div>

                <nav class="single-post-navigation no-margin" role="navigation">
                    <div class="row">

                        <div class="col-xs-6 col-sm-6 col-md-4">
                            <div class="previous-post-link">
                                {% if job_previous|length != 0 %}
                                    <a href="{{path('job_offer_show', { id: job_previous[0].id })}}" class="waves-effect waves-dark"><i class="fa fa-angle-left" aria-hidden="true"></i> Prev</a>
                                {% endif %}
                            </div>
                        </div>
                        <div class="hidden-xs hidden-sm col-md-4"></div>
                        <div class="col-xs-6 col-sm-6 col-md-4">
                            <div class="next-post-link">
                                {% if job_next|length != 0 %}
                                    <a href="{{path('job_offer_show', { id: job_next[0].id })}}" class="waves-effect waves-dark">Next <i class="fa fa-angle-right" aria-hidden="true"></i></a>
                                {% endif %}
                            </div>
                        </div>

                    </div>
                </nav>
            </div>
        </section>

    </div>

</div>

    <a class="btn bn-lg grey darken-1 btn-block waves-effect waves-light btn-register" href="{{ path('admin_job_offer_index') }}">back to list</a>

    {{ include('job_offer/_delete_form.html.twig') }}
{% endblock %}