src/Entity/Client.php
<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ClientRepository::class)
 */
class Client
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name_society;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $activity_type;

    /**
     * @ORM\OneToMany(targetEntity=JobOffer::class, mappedBy="id_client" )
     */
    private $jobOffers;

    public function __construct()
    {
        $this->infoAdminClients = new ArrayCollection();
        $this->jobOffers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameSociety(): ?string
    {
        return $this->name_society;
    }

    public function setNameSociety(string $name_society): self
    {
        $this->name_society = $name_society;

        return $this;
    }

    public function getActivityType(): ?string
    {
        return $this->activity_type;
    }

    public function setActivityType(string $activity_type): self
    {
        $this->activity_type = $activity_type;

        return $this;
    }

    /**
     * @return Collection|InfoAdminClient[]
     */
    public function getInfoAdminClients(): Collection
    {
        return $this->infoAdminClients;
    }

    public function addInfoAdminClient(InfoAdminClient $infoAdminClient): self
    {
        if (!$this->infoAdminClients->contains($infoAdminClient)) {
            $this->infoAdminClients[] = $infoAdminClient;
            $infoAdminClient->setIdClient($this);
        }

        return $this;
    }

    public function removeInfoAdminClient(InfoAdminClient $infoAdminClient): self
    {
        if ($this->infoAdminClients->removeElement($infoAdminClient)) {
            // set the owning side to null (unless already changed)
            if ($infoAdminClient->getIdClient() === $this) {
                $infoAdminClient->setIdClient(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|JobOffer[]
     */
    public function getJobOffers(): Collection
    {
        return $this->jobOffers;
    }

    public function addJobOffer(JobOffer $jobOffer): self
    {
        if (!$this->jobOffers->contains($jobOffer)) {
            $this->jobOffers[] = $jobOffer;
            $jobOffer->setClient($this);
        }

        return $this;
    }

    public function removeJobOffer(JobOffer $jobOffer): self
    {
        if ($this->jobOffers->removeElement($jobOffer)) {
            // set the owning side to null (unless already changed)
            if ($jobOffer->getClient() === $this) {
                $jobOffer->setClient(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->getNameSociety();
    }
}

src/Form/ClientType.php
<?php

namespace App\Form;

use App\Entity\Client;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ClientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name_society')
            ->add('activity_type')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Client::class,
        ]);
    }
}

src/Controller/ClientController.php
<?php

namespace App\Controller;

use App\Entity\Client;
use App\Form\ClientType;
use App\Repository\ClientRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/client")
 */
class ClientController extends AbstractController
{
    /**
     * @Route("/index", name="client_index", methods={"GET"})
     */
    public function index(ClientRepository $clientRepository): Response
    {
        return $this->render('client/index.html.twig', [
            'clients' => $clientRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="client_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $client = new Client();
        $form = $this->createForm(ClientType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($client);
            $entityManager->flush();

            return $this->redirectToRoute('client_index');
        }

        return $this->render('client/new.html.twig', [
            'client' => $client,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="client_show", methods={"GET"})
     */
    public function show(Client $client): Response
    {
        return $this->render('client/show.html.twig', [
            'client' => $client,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="client_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Client $client): Response
    {
        $form = $this->createForm(ClientType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('client_index');
        }

        return $this->render('client/edit.html.twig', [
            'client' => $client,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="client_delete", methods={"POST"})
     */
    public function delete(Request $request, Client $client): Response
    {
        if ($this->isCsrfTokenValid('delete'.$client->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($client);
            $entityManager->flush();
        }
        return $this->redirectToRoute('client_index');
    }
}

templates/client/_delete_form.html.twig
<form method="post" action="{{ path('client_delete', {'id': client.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ client.id) }}">
    <button class="btn bn-lg gradient red darken-3 btn-block waves-effect waves-light btn-register">Delete</button>
</form>

templates/client/_form.html.twig
{{ form_start(form) }}
    
   <section class="section-padding">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-6">
                    <div class="input-field">
                        {{ form_widget(form.name_society) }}
                        {{ form_label(form.name_society, 'name_society', {
                            'label_attr': {'class': 'name_society'}
                        }) }}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6">
                    <div class="input-field">
                        {{ form_widget(form.activity_type) }}
                        {{ form_label(form.activity_type, 'activity_type', {
                            'label_attr': {'class': 'activity_type'}
                        }) }}
                    </div>
                </div>
                <button class="btn bn-lg gradient primary btn-block waves-effect waves-light btn-register">{{ button_label|default('Save') }}</button>
            </div>
        </div>
    </section>
   
{{ form_end(form) }}

templates/client/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Client{% endblock %}

{% block body %}
    <h1 style="padding-top:10rem; text-align:center; background-color:#2F3138; margin-top:0; color:white; padding-bottom:2%">Edit Client</h1>

    {{ include('client/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('client_index') }}">back to list</a>

    {{ include('client/_delete_form.html.twig') }}
{% endblock %}

templates/client/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Client index{% endblock %}

{% block body %}
    <h1 style="padding-top:10rem; text-align:center; background-color:#2F3138; margin-top:0; color:white; padding-bottom:2%">Client index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name_society</th>
                <th>Activity_type</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for client in clients %}
            <tr>
                <td>{{ client.id }}</td>
                <td>{{ client.nameSociety }}</td>
                <td>{{ client.activityType }}</td>
                <td>
                    <a style="width:2vw; height:3vh; font-size:1rem; padding:initial" class="btn grey darken-1 waves-effect waves-light btn-register"  href="{{ path('client_show', {'id': client.id}) }}">show</a>
                    <a style="width:2vw; height:3vh; font-size:1rem; padding:initial" class="btn gradient secondary waves-effect waves-light btn-register" href="{{ path('client_edit', {'id': client.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn bn-lg grey darken-1 btn-block waves-effect waves-light btn-register" href="{{ path('client_new') }}">Create new</a>
    <a style="margin:0" target="_self" href="{{ path ('admin')}}" class="btn bn-lg gradient secondary btn-block waves-effect waves-light btn-register">
        <span> return to Admin Page</span>
    </a>
{% endblock %}

templates/client/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Client{% endblock %}

{% block body %}
    <h1  style="padding-top:10rem; text-align:center; background-color:#2F3138; margin-top:0; color:white; padding-bottom:2%">Create new Client</h1>

    {{ include('client/_form.html.twig') }}

    <a target="_self" href="{{ path('client_index') }}" class="btn bn-lg gradient secondary btn-block waves-effect waves-light btn-register">
        <span> back to list</span>
    </a>
    
{% endblock %}

templates/client/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Client{% endblock %}

{% block body %}
    <h1 style="padding-top:10rem; text-align:center; background-color:#2F3138; margin-top:0; color:white; padding-bottom:2%">Client</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ client.id }}</td>
            </tr>
            <tr>
                <th>Name_society</th>
                <td>{{ client.nameSociety }}</td>
            </tr>
            <tr>
                <th>Activity_type</th>
                <td>{{ client.activityType }}</td>
            </tr>
        </tbody>
    </table>

    <a class="btn bn-lg grey darken-1 btn-block waves-effect waves-light btn-register"  href="{{ path('client_index') }}">back to list</a>

    <a style="margin:0" class="btn bn-lg gradient secondary btn-block waves-effect waves-light btn-register" href="{{ path('client_edit', {'id': client.id}) }}">edit</a>

    {{ include('client/_delete_form.html.twig') }}
{% endblock %}