src/Entity/InfoAdminCandidat.php
<?php

namespace App\Entity;

use App\Repository\InfoAdminCandidatRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=InfoAdminCandidatRepository::class)
 */
class InfoAdminCandidat
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_created;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_updated;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_deleted;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $files;

    /**
     * @ORM\ManyToOne(targetEntity=Candidat::class , inversedBy="infoAdminCandidat")
     * @ORM\JoinColumn(nullable=false)
     */
    private $candidat;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateCreated(): ?\DateTimeInterface
    {
        return $this->date_created;
    }

    public function setDateCreated(\DateTimeInterface $date_created): self
    {
        $this->date_created = $date_created;

        return $this;
    }

    public function getDateUpdated(): ?\DateTimeInterface
    {
        return $this->date_updated;
    }

    public function setDateUpdated(\DateTimeInterface $date_updated): self
    {
        $this->date_updated = $date_updated;

        return $this;
    }

    public function getDateDeleted(): ?\DateTimeInterface
    {
        return $this->date_deleted;
    }

    public function setDateDeleted(\DateTimeInterface $date_deleted): self
    {
        $this->date_deleted = $date_deleted;

        return $this;
    }

    public function getFiles(): ?string
    {
        return $this->files;
    }

    public function setFiles(string $files): self
    {
        $this->files = $files;

        return $this;
    }

    public function getCandidat(): ?Candidat
    {
        return $this->candidat;
    }

    public function setCandidat(Candidat $candidat): self
    {
        $this->candidat = $candidat;

        return $this;
    }
}

src/Form/InfoAdminCandidatType.php
<?php

namespace App\Form;

use App\Entity\InfoAdminCandidat;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InfoAdminCandidatType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date_created')
            ->add('date_updated')
            ->add('date_deleted')
            ->add('files')
            ->add('candidat')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => InfoAdminCandidat::class,
        ]);
    }
}

src/Controller/InfoAdminCandidatController.php
<?php

namespace App\Controller;

use App\Entity\InfoAdminCandidat;
use App\Form\InfoAdminCandidatType;
use App\Repository\InfoAdminCandidatRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/info/admin/candidat")
 */
class InfoAdminCandidatController extends AbstractController
{
    /**
     * @Route("/", name="info_admin_candidat_index", methods={"GET"})
     */
    public function index(InfoAdminCandidatRepository $infoAdminCandidatRepository): Response
    {
        return $this->render('info_admin_candidat/index.html.twig', [
            'info_admin_candidats' => $infoAdminCandidatRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="info_admin_candidat_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $infoAdminCandidat = new InfoAdminCandidat();
        $form = $this->createForm(InfoAdminCandidatType::class, $infoAdminCandidat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($infoAdminCandidat);
            $entityManager->flush();

            return $this->redirectToRoute('info_admin_candidat_index');
        }

        return $this->render('info_admin_candidat/new.html.twig', [
            'info_admin_candidat' => $infoAdminCandidat,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="info_admin_candidat_show", methods={"GET"})
     */
    public function show(InfoAdminCandidat $infoAdminCandidat): Response
    {
        return $this->render('info_admin_candidat/show.html.twig', [
            'info_admin_candidat' => $infoAdminCandidat,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="info_admin_candidat_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, InfoAdminCandidat $infoAdminCandidat): Response
    {
        $form = $this->createForm(InfoAdminCandidatType::class, $infoAdminCandidat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('info_admin_candidat_index');
        }

        return $this->render('info_admin_candidat/edit.html.twig', [
            'info_admin_candidat' => $infoAdminCandidat,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="info_admin_candidat_delete", methods={"POST"})
     */
    public function delete(Request $request, InfoAdminCandidat $infoAdminCandidat): Response
    {
        if ($this->isCsrfTokenValid('delete'.$infoAdminCandidat->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($infoAdminCandidat);
            $entityManager->flush();
        }

        return $this->redirectToRoute('info_admin_candidat_index');
    }
}

templates/info_admin_candidat/_delete_form.html.twig
<form method="post" action="{{ path('info_admin_candidat_delete', {'id': info_admin_candidat.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ info_admin_candidat.id) }}">
    <button class="btn">Delete</button>
</form>

templates/info_admin_candidat/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/info_admin_candidat/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit InfoAdminCandidat{% endblock %}

{% block body %}
    <h1>Edit InfoAdminCandidat</h1>

    {{ include('info_admin_candidat/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('info_admin_candidat_index') }}">back to list</a>

    {{ include('info_admin_candidat/_delete_form.html.twig') }}
{% endblock %}

templates/info_admin_candidat/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}InfoAdminCandidat index{% endblock %}

{% block body %}
    <h1>InfoAdminCandidat index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_created</th>
                <th>Date_updated</th>
                <th>Date_deleted</th>
                <th>Files</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for info_admin_candidat in info_admin_candidats %}
            <tr>
                <td>{{ info_admin_candidat.id }}</td>
                <td>{{ info_admin_candidat.dateCreated ? info_admin_candidat.dateCreated|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ info_admin_candidat.dateUpdated ? info_admin_candidat.dateUpdated|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ info_admin_candidat.dateDeleted ? info_admin_candidat.dateDeleted|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ info_admin_candidat.files }}</td>
                <td>
                    <a href="{{ path('info_admin_candidat_show', {'id': info_admin_candidat.id}) }}">show</a>
                    <a href="{{ path('info_admin_candidat_edit', {'id': info_admin_candidat.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('info_admin_candidat_new') }}">Create new</a>
{% endblock %}

templates/info_admin_candidat/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New InfoAdminCandidat{% endblock %}

{% block body %}
    <h1>Create new InfoAdminCandidat</h1>

    {{ include('info_admin_candidat/_form.html.twig') }}

    <a href="{{ path('info_admin_candidat_index') }}">back to list</a>
{% endblock %}

templates/info_admin_candidat/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}InfoAdminCandidat{% endblock %}

{% block body %}
    <h1>InfoAdminCandidat</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ info_admin_candidat.id }}</td>
            </tr>
            <tr>
                <th>Date_created</th>
                <td>{{ info_admin_candidat.dateCreated ? info_admin_candidat.dateCreated|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date_updated</th>
                <td>{{ info_admin_candidat.dateUpdated ? info_admin_candidat.dateUpdated|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date_deleted</th>
                <td>{{ info_admin_candidat.dateDeleted ? info_admin_candidat.dateDeleted|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Files</th>
                <td>{{ info_admin_candidat.files }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('info_admin_candidat_index') }}">back to list</a>

    <a href="{{ path('info_admin_candidat_edit', {'id': info_admin_candidat.id}) }}">edit</a>

    {{ include('info_admin_candidat/_delete_form.html.twig') }}
{% endblock %}