src/Entity/InfoAdminClient.php
<?php

namespace App\Entity;

use App\Repository\InfoAdminClientRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=InfoAdminClientRepository::class)
 */
class InfoAdminClient
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity=Client::class, inversedBy="infoAdminClient")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_client;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $contact_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $contact_mail;

    /**
     * @ORM\Column(type="integer")
     */
    private $note;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdClient(): ?Client
    {
        return $this->id_client;
    }

    public function setIdClient(?Client $id_client): self
    {
        $this->id_client = $id_client;

        return $this;
    }

    public function getContactName(): ?string
    {
        return $this->contact_name;
    }

    public function setContactName(string $contact_name): self
    {
        $this->contact_name = $contact_name;

        return $this;
    }

    public function getContactMail(): ?string
    {
        return $this->contact_mail;
    }

    public function setContactMail(string $contact_mail): self
    {
        $this->contact_mail = $contact_mail;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(int $note): self
    {
        $this->note = $note;

        return $this;
    }
}

src/Form/InfoAdminClientType.php
<?php

namespace App\Form;

use App\Entity\InfoAdminClient;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InfoAdminClientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('contact_name')
            ->add('contact_mail')
            ->add('note')
            ->add('id_client')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => InfoAdminClient::class,
        ]);
    }
}

src/Controller/InfoAdminClientController.php
<?php

namespace App\Controller;

use App\Entity\InfoAdminClient;
use App\Form\InfoAdminClientType;
use App\Repository\InfoAdminClientRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/info/admin/client")
 */
class InfoAdminClientController extends AbstractController
{
    /**
     * @Route("/", name="info_admin_client_index", methods={"GET"})
     */
    public function index(InfoAdminClientRepository $infoAdminClientRepository): Response
    {
        return $this->render('info_admin_client/index.html.twig', [
            'info_admin_clients' => $infoAdminClientRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="info_admin_client_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $infoAdminClient = new InfoAdminClient();
        $form = $this->createForm(InfoAdminClientType::class, $infoAdminClient);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($infoAdminClient);
            $entityManager->flush();

            return $this->redirectToRoute('info_admin_client_index');
        }

        return $this->render('info_admin_client/new.html.twig', [
            'info_admin_client' => $infoAdminClient,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="info_admin_client_show", methods={"GET"})
     */
    public function show(InfoAdminClient $infoAdminClient): Response
    {
        return $this->render('info_admin_client/show.html.twig', [
            'info_admin_client' => $infoAdminClient,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="info_admin_client_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, InfoAdminClient $infoAdminClient): Response
    {
        $form = $this->createForm(InfoAdminClientType::class, $infoAdminClient);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('info_admin_client_index');
        }

        return $this->render('info_admin_client/edit.html.twig', [
            'info_admin_client' => $infoAdminClient,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="info_admin_client_delete", methods={"POST"})
     */
    public function delete(Request $request, InfoAdminClient $infoAdminClient): Response
    {
        if ($this->isCsrfTokenValid('delete'.$infoAdminClient->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($infoAdminClient);
            $entityManager->flush();
        }

        return $this->redirectToRoute('info_admin_client_index');
    }
}

templates/info_admin_client/_delete_form.html.twig
<form method="post" action="{{ path('info_admin_client_delete', {'id': info_admin_client.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ info_admin_client.id) }}">
    <button class="btn">Delete</button>
</form>

templates/info_admin_client/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/info_admin_client/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit InfoAdminClient{% endblock %}

{% block body %}
    <h1>Edit InfoAdminClient</h1>

    {{ include('info_admin_client/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('info_admin_client_index') }}">back to list</a>

    {{ include('info_admin_client/_delete_form.html.twig') }}
{% endblock %}

templates/info_admin_client/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}InfoAdminClient index{% endblock %}

{% block body %}
    <h1>InfoAdminClient index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Contact_name</th>
                <th>Contact_mail</th>
                <th>Note</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for info_admin_client in info_admin_clients %}
            <tr>
                <td>{{ info_admin_client.id }}</td>
                <td>{{ info_admin_client.contactName }}</td>
                <td>{{ info_admin_client.contactMail }}</td>
                <td>{{ info_admin_client.note }}</td>
                <td>
                    <a href="{{ path('info_admin_client_show', {'id': info_admin_client.id}) }}">show</a>
                    <a href="{{ path('info_admin_client_edit', {'id': info_admin_client.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('info_admin_client_new') }}">Create new</a>
{% endblock %}

templates/info_admin_client/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New InfoAdminClient{% endblock %}

{% block body %}
    <h1>Create new InfoAdminClient</h1>

    {{ include('info_admin_client/_form.html.twig') }}

    <a href="{{ path('info_admin_client_index') }}">back to list</a>
{% endblock %}

templates/info_admin_client/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}InfoAdminClient{% endblock %}

{% block body %}
    <h1>InfoAdminClient</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ info_admin_client.id }}</td>
            </tr>
            <tr>
                <th>Contact_name</th>
                <td>{{ info_admin_client.contactName }}</td>
            </tr>
            <tr>
                <th>Contact_mail</th>
                <td>{{ info_admin_client.contactMail }}</td>
            </tr>
            <tr>
                <th>Note</th>
                <td>{{ info_admin_client.note }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('info_admin_client_index') }}">back to list</a>

    <a href="{{ path('info_admin_client_edit', {'id': info_admin_client.id}) }}">edit</a>

    {{ include('info_admin_client/_delete_form.html.twig') }}
{% endblock %}